#!/usr/bin/env python3
"""Builds print-ready.pdf: a 2-page PDF (front, back) with crop marks at the
trim corners, generated by wrapping the existing front.svg/back.svg bleed
art on a larger canvas -- the card art itself is untouched."""
import os
import re
import subprocess

from generate import BLEED, DOC_W, DOC_H

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

MARGIN = 21.0        # extra canvas around the bleed box for crop marks (0.29in)
MARK_LEN = 12.0       # crop mark length, pt
MARK_GAP = 4.5        # gap between mark and the actual trim corner, pt
MARK_COLOR = "#000000"
MARK_WIDTH = 0.5

PAGE_W = DOC_W + 2 * MARGIN
PAGE_H = DOC_H + 2 * MARGIN
ART_X = MARGIN
ART_Y = MARGIN


def extract_inner(svg_text):
    m = re.search(r"<svg[^>]*>(.*)</svg>", svg_text, re.S)
    return m.group(1)


def crop_marks():
    # trim corners, in page coordinates
    tx0, ty0 = ART_X + BLEED, ART_Y + BLEED
    tx1, ty1 = ART_X + DOC_W - BLEED, ART_Y + DOC_H - BLEED
    marks = []
    for (cx, cy, sx, sy) in [
        (tx0, ty0, -1, -1), (tx1, ty0, 1, -1),
        (tx0, ty1, -1, 1), (tx1, ty1, 1, 1),
    ]:
        # horizontal mark
        x1 = cx + sx * MARK_GAP
        x2 = cx + sx * (MARK_GAP + MARK_LEN)
        marks.append(f'<line x1="{x1:.2f}" y1="{cy:.2f}" x2="{x2:.2f}" y2="{cy:.2f}" '
                      f'stroke="{MARK_COLOR}" stroke-width="{MARK_WIDTH}"/>')
        # vertical mark
        y1 = cy + sy * MARK_GAP
        y2 = cy + sy * (MARK_GAP + MARK_LEN)
        marks.append(f'<line x1="{cx:.2f}" y1="{y1:.2f}" x2="{cx:.2f}" y2="{y2:.2f}" '
                      f'stroke="{MARK_COLOR}" stroke-width="{MARK_WIDTH}"/>')
    return "\n  ".join(marks)


def build_page_svg(card_svg_path):
    inner = extract_inner(open(card_svg_path).read())
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{PAGE_W/72.0}in" height="{PAGE_H/72.0}in" viewBox="0 0 {PAGE_W} {PAGE_H}">
  <rect x="0" y="0" width="{PAGE_W}" height="{PAGE_H}" fill="#FFFFFF"/>
  <g transform="translate({ART_X},{ART_Y})">
  {inner}
  </g>
  {crop_marks()}
</svg>
'''


def main():
    front_page = build_page_svg(os.path.join(OUT_DIR, "front.svg"))
    back_page = build_page_svg(os.path.join(OUT_DIR, "back.svg"))

    front_svg_path = os.path.join(OUT_DIR, "_print_front.svg")
    back_svg_path = os.path.join(OUT_DIR, "_print_back.svg")
    open(front_svg_path, "w").write(front_page)
    open(back_svg_path, "w").write(back_page)

    front_pdf = os.path.join(OUT_DIR, "_print_front.pdf")
    back_pdf = os.path.join(OUT_DIR, "_print_back.pdf")
    subprocess.run(["rsvg-convert", "-f", "pdf", "-o", front_pdf, front_svg_path], check=True)
    subprocess.run(["rsvg-convert", "-f", "pdf", "-o", back_pdf, back_svg_path], check=True)

    out_pdf = os.path.join(OUT_DIR, "print-ready.pdf")
    subprocess.run(["pdfunite", front_pdf, back_pdf, out_pdf], check=True)

    for p in [front_svg_path, back_svg_path, front_pdf, back_pdf]:
        os.remove(p)

    print("wrote print-ready.pdf")


if __name__ == "__main__":
    main()
